import HeroSection from './components/HeroSection.jsx';
import Navbar from './components/Navbar.jsx';
import './globals.css';
import 'tailwindcss/tailwind.css';
export const metadata = {
  title: 'FITUP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
        {children}
      </body>
    </html>
  )
}
